// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA5S2BQ4tmFsquY0qJjJZSeDA5HszkqlU',
    appId: '1:512681659274:web:96033012310f45bc215673',
    messagingSenderId: '512681659274',
    projectId: 'login-auth-bloc',
    authDomain: 'login-auth-bloc.firebaseapp.com',
    storageBucket: 'login-auth-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO3utNJgzHN3jGxZMpgczERQ4iWt0-d-I',
    appId: '1:512681659274:android:28b346008f024a1e215673',
    messagingSenderId: '512681659274',
    projectId: 'login-auth-bloc',
    storageBucket: 'login-auth-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTkY-TU4gnPvdULPwzB99AKAD33ymdUJU',
    appId: '1:512681659274:ios:044374dd017c90e6215673',
    messagingSenderId: '512681659274',
    projectId: 'login-auth-bloc',
    storageBucket: 'login-auth-bloc.appspot.com',
    iosBundleId: 'com.example.loginAuthBloc',
  );
}
